// <auto-generated />
using System;
using System.Collections.Generic;
using BookingEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260919144756_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingEngine.Domain.Inventory.RatePlanRestriction", b =>
                {
                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_plan_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("ClosedToArrival")
                        .HasColumnType("boolean")
                        .HasColumnName("closed_to_arrival");

                    b.Property<bool>("ClosedToDeparture")
                        .HasColumnType("boolean")
                        .HasColumnName("closed_to_departure");

                    b.Property<int?>("MaxStay")
                        .HasColumnType("integer")
                        .HasColumnName("max_stay");

                    b.Property<int>("MinStayArrival")
                        .HasColumnType("integer")
                        .HasColumnName("min_stay_arrival");

                    b.Property<int>("MinStayThrough")
                        .HasColumnType("integer")
                        .HasColumnName("min_stay_through");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rate");

                    b.Property<bool>("StopSell")
                        .HasColumnType("boolean")
                        .HasColumnName("stop_sell");

                    b.HasKey("RatePlanId", "Date")
                        .HasName("pk_rate_plan_restrictions");

                    b.ToTable("rate_plan_restrictions", null, t =>
                        {
                            t.HasCheckConstraint("ck_rate_plan_restrictions_max_stay", "max_stay IS NULL OR max_stay >= 1");

                            t.HasCheckConstraint("ck_rate_plan_restrictions_min_stay_arrival", "min_stay_arrival >= 1");

                            t.HasCheckConstraint("ck_rate_plan_restrictions_min_stay_through", "min_stay_through >= 1");

                            t.HasCheckConstraint("ck_rate_plan_restrictions_rate", "rate IS NULL OR rate >= 0");
                        });
                });

            modelBuilder.Entity("BookingEngine.Domain.Inventory.RoomTypeAvailability", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.HasKey("RoomTypeId", "Date")
                        .HasName("pk_room_type_availability");

                    b.ToTable("room_type_availability", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_type_availability_availability", "availability >= 0");
                        });
                });

            modelBuilder.Entity("BookingEngine.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("BookingEngine.Domain.RatePlans.RatePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ChildFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("child_fee");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DerivedType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("derived_type");

                    b.Property<decimal?>("DerivedValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("derived_value");

                    b.Property<string>("MealPlan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal_plan");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentRatePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_rate_plan_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<string>("SellMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sell_mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_occupancies", "BookingEngine.Domain.RatePlans.RatePlan._occupancies#RatePlanOccupancy", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Adults");

                            b1.Property<decimal>("PriceAdjustment");

                            b1
                                .ToJson("occupancies")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_rate_plans");

                    b.HasIndex("ParentRatePlanId")
                        .HasDatabaseName("ix_rate_plans_parent_rate_plan_id");

                    b.HasIndex("RoomTypeId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_rate_plans_room_type_id_code");

                    b.ToTable("rate_plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_rate_plans_child_fee", "child_fee >= 0");

                            t.HasCheckConstraint("ck_rate_plans_derived_complete", "(parent_rate_plan_id IS NULL) = (derived_type IS NULL) AND (derived_type IS NULL) = (derived_value IS NULL)");
                        });
                });

            modelBuilder.Entity("BookingEngine.Domain.RoomTypes.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("CountOfRooms")
                        .HasColumnType("integer")
                        .HasColumnName("count_of_rooms");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("integer")
                        .HasColumnName("max_adults");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("integer")
                        .HasColumnName("max_children");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_room_types");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_room_types_property_id_code");

                    b.ToTable("room_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_types_count_of_rooms", "count_of_rooms >= 1");

                            t.HasCheckConstraint("ck_room_types_max_adults", "max_adults >= 1");

                            t.HasCheckConstraint("ck_room_types_max_children", "max_children >= 0");
                        });
                });

            modelBuilder.Entity("BookingEngine.Domain.Inventory.RatePlanRestriction", b =>
                {
                    b.HasOne("BookingEngine.Domain.RatePlans.RatePlan", null)
                        .WithMany()
                        .HasForeignKey("RatePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rate_plan_restrictions_rate_plans_rate_plan_id");
                });

            modelBuilder.Entity("BookingEngine.Domain.Inventory.RoomTypeAvailability", b =>
                {
                    b.HasOne("BookingEngine.Domain.RoomTypes.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_type_availability_room_types_room_type_id");
                });

            modelBuilder.Entity("BookingEngine.Domain.RatePlans.RatePlan", b =>
                {
                    b.HasOne("BookingEngine.Domain.RatePlans.RatePlan", null)
                        .WithMany()
                        .HasForeignKey("ParentRatePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rate_plans_rate_plans_parent_rate_plan_id");

                    b.HasOne("BookingEngine.Domain.RoomTypes.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rate_plans_room_types_room_type_id");
                });

            modelBuilder.Entity("BookingEngine.Domain.RoomTypes.RoomType", b =>
                {
                    b.HasOne("BookingEngine.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_types_properties_property_id");
                });
#pragma warning restore 612, 618
        }
    }
}
