apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-engine-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts: ["booking.example.com"]
      secretName: booking-engine-tls
  rules:
    - host: booking.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: booking-engine-api
                port:
                  name: http
